### PR TITLE
Feat/store access token in cookie

### PR DESCRIPTION
**Pull request by timber-they**
Also note the [UI PR](https://github.com/mint-o-badges/badgr-ui/pull/851)

### CODE REVIEW

**Comment by timber-they** [comment]
I asked @zven about it. Btw, @jona159 did you also review the [UI PR](https://github.com/mint-o-badges/badgr-ui/pull/851)?

**Comment by jona159** [comment]
> I asked @zven about it. Btw, @jona159 did you also review the [UI PR](https://github.com/mint-o-badges/badgr-ui/pull/851)?

Yes, it's approved now

**Comment by zven** [comment]
@jona159 As I (just now) communicated to @timber-they, I don't see a big problem here. Worst case scenario: We (who do stuff regularly in the admin panel) might stumble over this.

I see the compatibility with OIDC as a separate (future) topic, since we don't have that use case at the moment.

While typing this, one other thing comes to my mind: Does this feature interfere with the login of external platforms (like that moodle plugin) that use OAuth credentials?

**Comment by timber-they** [comment]
@zven since the "old" mechanisms still work for login, this shouldn't interfere.

**Comment by timber-they** [comment]
@jona159 you still need to formally approve it

**Review by jona159 — APPROVED** [review]

**Pull request merged**
