### PR TITLE
Feat edit pdf

### PR DESCRIPTION
**Pull request by Thiemann96**
According [#716](https://github.com/mint-o-badges/badgr-ui/issues/716) edited the pdf

 - Added italic font 
 - edited pdf certificate according to figma 
 - changes competencie studyload to hours:minutes according to #272

### CODE REVIEW

**Comment by jona159** [comment]
Some observations: 
- Please remove the import of ```AllPageSetup``` in the ```account_adapter.py ``` file. 
- When i try to award a badge i get this error: 
```
badgr-server-api-1        | [01/Nov/2024 02:35:05] "OPTIONS /v1/issuer/issuers/dBCl-cYLQs-e9rp9blHtLA/badges/vLcOAb_nQ52heRt_V2IOrQ/assertions HTTP/1.1" 200 0
badgr-server-api-1        | Internal Server Error: /v1/issuer/issuers/dBCl-cYLQs-e9rp9blHtLA/badges/vLcOAb_nQ52heRt_V2IOrQ/assertions
badgr-server-api-1        | Traceback (most recent call last):
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
badgr-server-api-1        |     response = get_response(request)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
badgr-server-api-1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
badgr-server-api-1        |     return view_func(*args, **kwargs)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
badgr-server-api-1        |     return self.dispatch(request, *args, **kwargs)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
badgr-server-api-1        |     response = self.handle_exception(exc)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
badgr-server-api-1        |     self.raise_uncaught_exception(exc)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
badgr-server-api-1        |     raise exc
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
badgr-server-api-1        |     response = handler(request, *args, **kwargs)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/apispec_drf/decorators.py", line 154, in wrapper
badgr-server-api-1        |     return wrapped(*args, **kwargs)
badgr-server-api-1        |   File "/badgr_server/apps/issuer/api.py", line 552, in post
badgr-server-api-1        |     return super(BadgeInstanceList, self).post(request, **kwargs)
badgr-server-api-1        |   File "/badgr_server/apps/entity/api.py", line 90, in post
badgr-server-api-1        |     new_instance = serializer.save(created_by=request.user)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
badgr-server-api-1        |     self.instance = self.create(validated_data)
badgr-server-api-1        |   File "/badgr_server/apps/issuer/serializers_v1.py", line 533, in create
badgr-server-api-1        |     return self.context.get('badgeclass').issue(
badgr-server-api-1        |   File "/badgr_server/apps/issuer/models.py", line 883, in issue
badgr-server-api-1        |     return BadgeInstance.objects.create(
badgr-server-api-1        |   File "/badgr_server/apps/issuer/managers.py", line 349, in create
badgr-server-api-1        |     new_instance.notify_earner(badgr_app=badgr_app)
badgr-server-api-1        |   File "/badgr_server/apps/issuer/models.py", line 1264, in notify_earner
badgr-server-api-1        |     pdf_document = adapter.generate_pdf_content(slug =  self.entity_id)
badgr-server-api-1        |   File "/badgr_server/apps/mainsite/account_adapter.py", line 146, in generate_pdf_content
badgr-server-api-1        |     doc.build(Story, canvasmaker=PageNumCanvas)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1314, in build
badgr-server-api-1        |     BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1079, in build
badgr-server-api-1        |     self.handle_flowable(flowables)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 928, in handle_flowable
badgr-server-api-1        |     if frame.add(f, canv, trySplit=self.allowSplitting):
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/frames.py", line 212, in _add
badgr-server-api-1        |     flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/flowables.py", line 112, in drawOn
badgr-server-api-1        |     self._drawOn(canvas)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/flowables.py", line 93, in _drawOn
badgr-server-api-1        |     self.draw()#this is the bit you overload
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/tables.py", line 1666, in draw
badgr-server-api-1        |     self._drawCell(cellval, cellstyle, (colpos, rowpos), (colwidth, rowheight))
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/tables.py", line 1803, in _drawCell
badgr-server-api-1        |     v.drawOn(self.canv,x,y)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/flowables.py", line 112, in drawOn
badgr-server-api-1        |     self._drawOn(canvas)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/platypus/flowables.py", line 93, in _drawOn
badgr-server-api-1        |     self.draw()#this is the bit you overload
badgr-server-api-1        |   File "/badgr_server/apps/backpack/views.py", line 85, in draw
badgr-server-api-1        |     canvas.drawImage(
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/pdfgen/canvas.py", line 980, in drawImage
badgr-server-api-1        |     imgObj = pdfdoc.PDFImageXObject(name, image, mask=mask)
badgr-server-api-1        |   File "/usr/local/lib/python3.8/site-packages/reportlab/pdfbase/pdfdoc.py", line 2078, in __init__
badgr-server-api-1        |     ext = os.path.splitext(source)[1].lower()
badgr-server-api-1        |   File "/usr/local/lib/python3.8/posixpath.py", line 118, in splitext
badgr-server-api-1        |     p = os.fspath(p)
badgr-server-api-1        | TypeError: expected str, bytes or os.PathLike object, not FieldFile
badgr-server-api-1        | [01/Nov/2024 02:35:07] "POST /v1/issuer/issuers/dBCl-cYLQs-e9rp9blHtLA/badges/vLcOAb_nQ52heRt_V2IOrQ/assertions HTTP/1.1" 500 25741
```

On first glance the error seems to be related to the custom flowable ```roundedImage```. I think we might not actually need this as there is a way to create a table with rounded corners by using the ```cornerRadii```attribute (see ```views.py``` in the backpack app, line 454)

**Review by jona159 — CHANGES_REQUESTED** [review]
please consider suggestions from the comment above

**Comment by Thiemann96** [comment]
I see. I'll have a look into it and may move the qr code creation to backend

**Comment by Thiemann96** [comment]
MOVED TO #281

**Pull request closed without merging**
