### PR TITLE
Feat/restyle simple badge award email

### PR DESCRIPTION
**Pull request by jona159**
implement [figma design](https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5081-41085&t=zXbUEUPlYEvaRBbw-0) for new badge notification email

### CODE REVIEW

**Review by YouQam — COMMENTED** [review]
@jona159 @zven  Is there a list of email clients that I should review this PR in?

**Review by YouQam — CHANGES_REQUESTED** [review]
There are three main things that need to be updated/adjusted (missing parts, styles and broken icons). The updates differ form a client to another. I tested this PR with 4 clients (Mail, Gmail, WebMail and Outlook). The attached image includes the summary of the requested updated/adjustments.
Screenshot 2024-07-12 at 19 38 45

**Review by YouQam — CHANGES_REQUESTED** [review]
Now It looks better with all 4 clients. Ignoring broken images which is out of this PR scope, one last thing to update is to make competencies width align with `Meinen Badge speichern` btn.
Screenshot 2024-07-17 at 15 03 44

**Comment by jona159** [comment]
> Now It looks better with all 4 clients. Ignoring broken images which is out of this PR scope, one last thing to update is to make competencies width align with `Meinen Badge speichern` btn. Screenshot 2024-07-17 at 15 03 44

I think it should be fixed now, but not 100% sure because i cant test on develop as disk space is full

**Comment by YouQam** [comment]
> > Now It looks better with all 4 clients. Ignoring broken images which is out of this PR scope, one last thing to update is to make competencies width align with `Meinen Badge speichern` btn. Screenshot 2024-07-17 at 15 03 44
> 
> I think it should be fixed now, but not 100% sure because i cant test on develop as disk space is full

Yes, it was fixed.

**Pull request merged**
